### ISSUE TITLE
Retire?

### ISSUE THREAD

**Issue by loklaan** [zeeeeee/firefox-elementary#14]
Hey @zeeeeee !

Long time :)

Want to retire this theme? Or, put it up for grabs for another maintainer?

I have not used Elementary in quite awhile, so I no longer really can contribute to any further maintenance if you want to keep the project around.

Cheers.

**Comment by zeeeeee** [comment]
Hi Loklaan! Long time indeed..

I wouldn't mind leaving the theme for another maintainer, but this isn't
even the latest build, because I stopped committing changes here before I
announced my retirement.. The latest build can be downloaded at Mozilla. So
probably it would be better to retire the theme here. What do you think?
I'd appreciate any help doing that, because I've also stopped using
elementary, or Linux, for that matter.

Great to hear from you. Cheers!




2016-02-07 9:42 GMT+00:00 Lochlan Bunn <notifications@github.com>:

> Hey @zeeeeee <https://github.com/zeeeeee> !
>
> Long time :)
>
> Want to retire this theme? Or, put it up for grabs for another maintainer?
>
> I have not used Elementary in quite awhile, so I no longer really can
> contribute to any further maintenance if you want to keep the project
> around.
>
> Cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeeeeee/firefox-elementary/issues/14>.
>



-- 
Jose California | arquitecto
Cc. Galvao 13, 2Do. 1400-162 Lisboa
T +351_966 870 234

**Comment by loklaan** [comment]
I'll update the README with a retirement notice. :) Stay cool.

**Comment by zeeeeee** [comment]
Thanks! :)

2016-02-13 15:27 GMT+00:00 Lochlan Bunn <notifications@github.com>:

> I'll update the README with a retirement notice. :) Stay cool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeeeeee/firefox-elementary/issues/14#issuecomment-183686227>
> .
>



-- 
Jose California | arquitecto
Cc. Galvao 13, 2Do. 1400-162 Lisboa
T +351_966 870 234
